-- =============================================================================
-- Build the admission cutoffs used by the competition validation dataset.
--
-- Source of truth:
--   major_admission_cutoff rows whose data_kind is SIMULATED.
--
-- Rules:
--   1. Hunan history rows are derived only from Hunan physics SIMULATED rows
--      whose linked major is explicitly marked as subject_requirement='不限'.
--      Physics/chemistry-only rows and rows without a linked major are skipped.
--   2. The history score offset is deterministic and reproducible:
--        physics score - (6 + MOD(university_id + major_id, 9)).
--   3. A university cutoff is the minimum major cutoff for the same
--      university/year/province/subject.
--   4. Rank is looked up by that exact score in score_rank_mapping. Missing
--      mappings remain NULL; fabricated or negative ranks are never retained.
--   5. The legacy admission_cutoff seed is replaced because it was generated by
--      a separate formula and is not consistent with the major-level source.
--
-- This file is mounted only under docker-entrypoint-initdb.d and is intended for
-- a brand-new local competition database, not as a production upgrade script.
-- =============================================================================

-- Set the client charset explicitly: docker-entrypoint-initdb.d runs this file
-- with a non-utf8mb4 default client charset, which mojibakes the Chinese
-- literals below (calibration_source / simulation_rule).
SET NAMES utf8mb4;

START TRANSACTION;

INSERT INTO major_admission_cutoff (
  university_id,
  major_id,
  major_name,
  admission_year,
  province,
  subject_type,
  cutoff_score,
  min_rank,
  plan_count,
  duration_years,
  tuition_per_year,
  data_kind,
  calibration_source,
  simulation_rule,
  simulation_seed
)
SELECT physics.university_id,
       physics.major_id,
       physics.major_name,
       physics.admission_year,
       physics.province,
       '历史',
       GREATEST(
         0,
         physics.cutoff_score - (6 + MOD(physics.university_id + physics.major_id, 9))
       ),
       NULL,
       CASE
         WHEN physics.plan_count IS NULL THEN NULL
         ELSE GREATEST(1, ROUND(physics.plan_count * 0.65))
       END,
       physics.duration_years,
       physics.tuition_per_year,
       'SIMULATED',
       '湖南物理比赛验证专业线；仅用于生成湖南历史比赛验证切片，不是官方历史录取数据',
       'HN-HISTORY-DEMO-V1: 仅选科不限；历史分=物理演示分-(6+MOD(学校ID+专业ID,9))',
       CRC32(CONCAT('HN-HISTORY-DEMO-V1:', physics.university_id, ':', physics.major_id))
FROM major_admission_cutoff AS physics
JOIN major AS linked_major
  ON linked_major.id = physics.major_id
WHERE physics.province = '湖南'
  AND physics.subject_type = '物理'
  AND physics.data_kind = 'SIMULATED'
  AND physics.cutoff_score IS NOT NULL
  AND linked_major.subject_requirement = '不限'
ON DUPLICATE KEY UPDATE
  major_id = VALUES(major_id),
  cutoff_score = VALUES(cutoff_score),
  min_rank = VALUES(min_rank),
  plan_count = VALUES(plan_count),
  duration_years = VALUES(duration_years),
  tuition_per_year = VALUES(tuition_per_year),
  data_kind = VALUES(data_kind),
  calibration_source = VALUES(calibration_source),
  simulation_rule = VALUES(simulation_rule),
  simulation_seed = VALUES(simulation_seed);

UPDATE major_admission_cutoff AS major_cutoff
LEFT JOIN score_rank_mapping AS score_rank
  ON score_rank.mapping_year = major_cutoff.admission_year
 AND score_rank.province = major_cutoff.province
 AND score_rank.subject_type = major_cutoff.subject_type
 AND score_rank.score = major_cutoff.cutoff_score
SET major_cutoff.min_rank = CASE
      WHEN score_rank.rank_value > 0 THEN score_rank.rank_value
      ELSE NULL
    END,
    major_cutoff.calibration_source = COALESCE(
      NULLIF(major_cutoff.calibration_source, ''),
      '湖南省公开投档线与一分一段分布仅用于比赛验证数据的区间校准；当前记录不是官方专业录取线'
    ),
    major_cutoff.simulation_rule = COALESCE(
      NULLIF(major_cutoff.simulation_rule, ''),
      '比赛验证数据：专业分为演示值；位次按同口径一分一段表映射'
    )
WHERE major_cutoff.data_kind = 'SIMULATED';

DELETE FROM admission_cutoff;

INSERT INTO admission_cutoff (
  university_id,
  admission_year,
  province,
  subject_type,
  cutoff_score,
  min_rank
)
SELECT derived.university_id,
       derived.admission_year,
       derived.province,
       derived.subject_type,
       derived.cutoff_score,
       CASE
         WHEN score_rank.rank_value > 0 THEN score_rank.rank_value
         ELSE NULL
       END AS min_rank
FROM (
  SELECT university_id,
         admission_year,
         province,
         subject_type,
         MIN(cutoff_score) AS cutoff_score
  FROM major_admission_cutoff
  WHERE data_kind = 'SIMULATED'
    AND cutoff_score IS NOT NULL
  GROUP BY university_id, admission_year, province, subject_type
) AS derived
LEFT JOIN score_rank_mapping AS score_rank
  ON score_rank.mapping_year = derived.admission_year
 AND score_rank.province = derived.province
 AND score_rank.subject_type = derived.subject_type
 AND score_rank.score = derived.cutoff_score
ORDER BY derived.university_id,
         derived.admission_year,
         derived.province,
         derived.subject_type;

COMMIT;
